config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/admin', to: 'pages#admin', as: 'admin'
  get "/autocomplete", to: 'cities#autocomplete'
  get "/contact_us", to: 'pages#contact_us'
  get 'city_clubs/:id', to: 'cities#city_clubs'
  get 'city_clubs', to: 'cities#city_clubs_redirect'
  
  resources :suggestions
  resources :countries do
    member do 
      patch :deactivate_country
    end
  end
  
  resources :cities do 
    member do 
      patch :deactivate_city
    end
  end
  
  resources :clubs do
    resources :reviews, only: [:create]
    member do 
      patch :deactivate_club
    end
  end
  resources :features, only: [:create, :destroy]
  resources :reviews, only: [:update, :edit, :show, :destroy]
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_modal.html.erb
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style = "border-radius: 10px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Review <%= @club.name %></h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class ="row">
        <div class="col-md-2"></div>
        <div class="col-md-10">    
          <div class="modal-body text-center">
            <%= simple_form_for([@club, Review.new]) do |f| %>
              <div class="form-group">
                <input type="text" class="form-control" id="name" name="name" placeholder="Please Enter Your name">
              </div>
              <div class="form-group">

              <input type="email" class="form-control" id="email" name="email" placeholder="Please Enter Your email">
              </div>
              <input type="hidden" class="form-control" id="stars_id" name="stars">
              <p class="review_rating">
                Give it a rating
                <i id="review_star_1" onclick="review_star('1')" class="fa fa-star stars ml-3" style = "color: black;"></i>
                <i id="review_star_2" onclick="review_star('2')" class="fa fa-star stars"></i style = "color: black;">
                <i id="review_star_3" onclick="review_star('3')" class="fa fa-star stars"></i style = "color: black;">
                <i id="review_star_4" onclick="review_star('4')" class="fa fa-star stars"></i style = "color: black;">
                <i id="review_star_5" onclick="review_star('5')" class="fa fa-star stars"></i style = "color: black;">
              </p>
              
              <div class="form-group">
                <textarea class="form-control" rows="5" id="content" name="content" placeholder= "Write your review"></textarea>
              </div>

              <div>
                <%= recaptcha_tags %> <!-- THIS -->
              </div>
          
              <%= f.submit class: 'btn btn-vibe ' %>
            <% end %>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon sticky-top">
    <a href="/" style="color: white;" class="navbar-brand">VIBE CLUBS</a>


  <div class="" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
        
        <div class="dropdown">
          <a class="btn btn-vibe dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            My account
          </a>

          <div class="dropdown-menu" aria-labelledby="dropdownMenuLink" style="position:absolute">
            <%= link_to "Dashboard", dashboard_path, class: "dropdown-item" %>
            <%= link_to "List a club", new_club_path, class: "dropdown-item" %>
            <%= link_to 'Edit account', edit_user_registration_path, class: 'dropdown-item' %>
            <%= link_to "Log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </div>
      <% else %>
        <div class="dropdown" >
          <div class="dropbtn ml-4"> <i class="fas fa-bars fa-2x"  style = "margin-right:0px"></i></div>
          <div class="dropdown-content">
            <%= link_to 'Log in', new_user_session_path, class: 'dropdown-item' %>
            <%= link_to "Sign up", new_user_registration_path, class: "dropdown-item" %>
          </div>
        </div>
      <% end %>
    </ul>
  </div>
</div>

<div class="modal fade" id="contact_us" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style = "border-radius: 10px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Contact Us</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class ="row">
        <div class="col-md-2"></div>
        <div class="col-md-10">    
          <div class="modal-body text-center">
            <%= form_tag(contact_us_path, method: "get") do %> 
              <div class="form-group">
                <input type="text" class="form-control" id="name" name="name" placeholder="Please Enter Your name">
              </div>
              <div class="form-group">

              <input type="email" class="form-control" id="email" name="email" placeholder="Please Enter Your email">
              </div>

              <div class="form-group">
                <textarea class="form-control" rows="5" id="content" name="content" placeholder= "Write your query"></textarea>
              </div>
              
              <div>
                <%= recaptcha_tags %> <!-- THIS -->
              </div>

              <button type="submit" class="btn btn-vibe">Submit</button>

            <% end %>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="modal fade" id="suggestion" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content" style = "border-radius: 10px;">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Please Sugest City and Country</h5>
        
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class ="row">
        <div class="col-md-1"></div>
        <div class="col-md-10">    
          <div class="modal-body">
            <%= form_tag(suggestions_path, method: "post") do %> 
              <div class="form-group">
                <input type="text" class="form-control" id="city" name="city" placeholder="Please Enter City Name">
              </div>
              <div class="form-group">

              <input type="text" class="form-control" id="country" name="country" placeholder="Please Enter Country Name">
              </div>
            
              <button type="submit" class="btn btn-vibe">Submit</button>

            <% end %>
          </div>
          <div class="col-md-1"></div>
        </div>
      </div>
    </div>
  </div>
</div>