config/routes.rb
Rails.application.routes.draw do
  get '/dashboard', to: 'pages#dashboard', as: 'dashboard'
  get '/admin', to: 'pages#admin', as: 'admin'
  get "/autocomplete", to: 'cities#autocomplete'
  get "/contact_us", to: 'pages#contact_us'
  get 'city_clubs/:id', to: 'cities#city_clubs'
  get 'city_clubs', to: 'cities#city_clubs_redirect'
  
  resources :suggestions
  resources :countries do
    member do 
      patch :deactivate_country
    end
  end
  
  resources :cities do 
    member do 
      patch :deactivate_city
    end
  end
  
  resources :clubs do
    resources :reviews, only: [:create]
    member do 
      patch :deactivate_club
    end
  end
  resources :features, only: [:create, :destroy]
  resources :reviews, only: [:update, :edit, :show, :destroy]
  devise_for :users
  root to: 'pages#home'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/admin.html.erb
<div class="container">
  <div class="row my-5" id="accordionExample">
    <div  class="col-sm-12 col-lg-4">
        <button class="btn  btn-success btn-block text-left" type="button" data-toggle="collapse" data-target="#collapseOne" aria-expanded="true" aria-controls="collapseOne">
          Create a new Country
        </button>

      <div id="collapseOne" class="collapse" aria-labelledby="headingOne" data-parent="#accordionExample">
      <div class="card-body">
        <%= simple_form_for(@country) do |f| %>
        <%= f.input :name, placeholder: 'Country name', label: false %>
        <%= f.input :image, placeholder: 'Paste Image address', label: false %>
        <%= f.submit class: 'btn btn-success' %>
      <% end %>
      </div>
    </div>
    </div>
    <div class="col-sm-12 col-lg-4">
      <button class="btn btn-success btn-block text-left collapsed" type="button" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="false" aria-controls="collapseTwo">
          Create new city
        </button>

        <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionExample">
      <div class="card-body">
      <%= simple_form_for(@city) do |f| %>
        <%= f.input :name, placeholder: 'City name', label: false %>
        <%= f.input :image, placeholder: 'Paste image address', label: false %>
        <%= f.association :country, include_blank: false, label: false %>
        <%= f.submit class: 'btn btn-success'%>
      <% end %>
      </div>
    </div>
    </div>

    <div class="col-sm-12 col-lg-4">
      <div class="form-box">
        <h5>Featured Club</h5>
        <div class="dropdown">
          <button class="btn btn-secondary dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Add a new
          </button>
          <div class="dropdown-menu p-1" aria-labelledby="dropdownMenuButton">
            <% Club.order(name: :desc).each do |club| %>
              <%= link_to club.name, features_path(id: club.id), method: :post, class: 'dropdown-item' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="row my-5">
    <h2 class="col-12">Counts</h2>
    <div class="col">
      <div class="box-count">
        <h2><%= User.count %> Users</h2>
      </div>
    </div>
    <div class="col">
      <div class="box-count">
        <h2><%= City.count %> Cities</h2>
      </div>
    </div>
      <div class="col">
        <div class="box-count">
        <h2><%= Review.count %> Reviews</h2>
      </div>
      </div>
      <div class="col">
        <div class="box-count">
          <h2><%= Country.count %> Countries</h2>
        </div>
      </div>
    </div>


</div>
  </div>


<div class="container">
  <div class="row form-box">
  <div class="col-sm-12 col-lg-6">
    <table class="table">
  <thead>
    <tr>
      <th scope="col">City</th>
      <th scope="col">Clubs in the city</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% City.all.each do |city| %>
    <tr>
      <td><%= city.name %></td>
      <td><%= city.clubs.count %></td>
      <td>
        <%= link_to 'Edit', edit_city_path(city), class: 'btn btn-warning mr-1' %>
        <%= link_to 'Delete', city, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </td>
    </tr>
    <%  end %>

  </tbody>
</table>
  </div>

  <div class="col-sm-12 col-lg-6">
    <table class="table">
  <thead>
    <tr>
      <th scope="col">Country</th>
      <th scope="col">Cities in the country</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% Country.all.each do |country| %>
    <tr>
      <td><%= country.name %></td>
      <td><%= country.cities.count %></td>
      <td>
        <%= link_to 'Edit', edit_country_path(country), class: 'btn btn-warning mr-1' %>
        <%= link_to 'Delete', country, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </td>
    </tr>
    <%  end %>

  </tbody>
</table>
  </div>
</div>




<div class="row my-5 form-box">
  <h2 class="col-12">Reviews</h2>
  <div class="col-12 ">
    <table class="table ">
  <thead>
    <tr>
      <th scope="col">Reviewer</th>
      <th scope="col">Content</th>
      <th scope="col">Stars</th>
      <th scope="col">Club</th>
      <th scope="col">Confirmed</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% Review.all.each do |review| %>
    <tr>
      <td><%= review.email %></td>
      <td><%= review.content %></td>
      <td><%= review.club.name %></td>
      <td><%= review.stars %> stars</td>
      <td><%= review.confirmed ? 'Yes' : 'No' %></td>
      <td>
        <%= link_to 'Delete', review, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger' %>
      </td>
    </tr>
    <%  end %>

  </tbody>
</table>
  </div>
</div>
</div>

app/views/pages/dashboard.html.erb
<div class="container my-5">
  <div class="row">
    <h2 class="col-12">Here are the clubs you have listed: </h2>
    <% current_user.clubs.each do |club| %>
        <div class="col-sm-12 col-lg-4">
          <%= link_to club do  %>
          <div class="card-club">
            <div class="card-img p-2" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)),url('<%= cl_image_path club.photos.first.key %>')">
          </div>
            <div class="card-description p-1 d-flex justify-content-between">
              <h2 style="line-height: 1rem;"  class="mt-1 card-title"><%= club.name.truncate(14) %></h2>
              <p class="m-2"><%= club.city.name %></p>
            </div>
            <p style="line-height: 0.1rem;" class="ml-1">
                <% 5.times do |x| %>
                  <i class="fa fa-star stars" style="color: <%= x < club.average_rating ? '#f5bb1b' : 'grey'  %>;"></i>
                <% end %>
              (<%= club.reviews.count %> <%= 'Review'.pluralize(club.reviews.count) %>)
              </p>
          </div>
          <% end %>
          <%= link_to 'Edit', edit_club_path(club), class: 'btn btn-warning' %>
          <%= link_to 'Delete', club, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'  %>
        </div>
      <% end %>
  </div>
</div>

app/views/pages/home.html.erb
<div  class="banner" style="background-image:linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('https://images.unsplash.com/photo-1605170876472-db58e15c430e?ixid=MXwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHw%3D&ixlib=rb-1.2.1&auto=format&fit=crop&w=1050&q=80'); height: 100%; background-position: center; background-repeat: no-repeat; background-size: cover; transform: scale(1.1);">
  <div data-controller="autocomplete" class="container" style="padding-top:130px">
    <img class= "card-img" src= "<%= image_path('logo-updated.png')%>" style="margin-bottom: 0.5em; margin-left: -0.9em; width: 105%;"/>
    <h3 style="color:white;font-size: 6vw;">Find the best nightlife</h3>
    <p style="color:white;font-size: 4vw;">RnB | Hip Hop | All Urban </p> 
      <form class="mx-auto"  action="/clubs">
        <input id="search-input" onblur="addText('#search-input')" onfocus="removeText('#search-input')" data-target="autocomplete.input" data-action="keyup->autocomplete#fetchCities" class=" w-100 text-center" type="text" autocomplete="off" name="city" placeholder="Search for a City">
        <ul class="suggestions" data-target="autocomplete.suggestions" class="autocomplete">
      </ul>
   </div>

    

      <script>
        const removeText = (id) => {
          let input = document.querySelector(id)
          input.placeholder = ''
          input.classList.remove('text-center')
        }

        const addText = (id) => {
          let input = document.querySelector(id)
          input.placeholder = 'Search for a city'
          input.classList.add('text-center')
        }
      </script>

      <p style="color: white;font-size: 4vw;" class="mt-3">Or</p>
      <%= link_to 'See all Countries', countries_path, class: 'btn btn-vibe', style: 'width: 300px;margin-bottom: 50%' %>
  </div>
</div>

<div class="container my-5 ">
  <div class="row" style="margin-top:13%">
    <h2 class="col-sm-12 text-center heading-2">Popular Cities</h2>
  </div>
  <div class="row">
    <% @cities.each do |city| %>
        <div class="col-sm-12 col-lg-4">
          <%= link_to city do  %>
          <div class="card-country" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)),url('<%= city.image %>')">
            <h2 style="color: white;" class="card-title"><%= city.name %></h2>
          </div>
          <% end %>
        </div>
      <% end %>
  </div>

  <div class="row my-4">
    <h2 class="col-12 text-center heading-2">Featured Clubs</h2>
      <% @featured.each do |featured| %>
        <div class="col-sm-12 col-lg-4">
          <%= link_to featured.club do  %>
          <div class="card-club">
            <div class="card-img" style="background-image: linear-gradient(rgba(0,0,0,0.3),rgba(0,0,0,0.3)),url('<%= cl_image_path featured.club.photos.first.key %>')">
            </div>
            <div class="card-description p-1 d-flex justify-content-between">
              <h2 style="line-height: 1rem;" class="mt-1 card-title"><%= featured.club.name.truncate(11) %></h2>
              <p class="m-2"><%= featured.club.city.name %></p>
            </div>
            <p class="ml-1">
                <% 5.times do |x| %>
                  <i class="fa fa-star stars" style="color: <%= x < featured.club.average_rating ? '#f5bb1b' : 'grey'  %>;"></i>
                <% end %>
              (<%= featured.club.reviews.count %> <%= 'Review'.pluralize(featured.club.reviews.count) %>)
              </p>

          </div>
          <% end %>
          <% if current_user && current_user.admin == true %>
            <%= link_to 'Delete', featured, method: :delete, data: { confirm: "Are you sure?" }, class: 'btn btn-danger'  %>
          <% end %>
          </div>
      <% end %>
  </div>

<hr>

  <div class="row text-center">
    <h2 class="col-12 heading-2">Are you a promoter?</h2>
    <h4 class="col-12">
      List your events and reach thousands in your city.
    </h4>
    <div class="col-sm-12 col-lg-4 mx-auto">
      <%= link_to 'List my event', '', class: 'btn btn-secondary' %>
    </div>

  </div>
</div>